{"success":false,"status_code":500,"error":"An error occurred","traceback":"Traceback (most recent call last):\n  File \"/home/GetLinkBackend/helpers/utils/advice.py\", line 30, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/GetLinkBackend/user_profile/views.py\", line 258, in post\n    reset_password = User.reset_password(**serializer.validated_data)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/GetLinkBackend/user_profile/models.py\", line 339, in reset_password\n    expiry_date = verify.date_created + timedelta(minutes=verify.expiry_time)\n                  ^^^^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'date_created'\n"}